version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: movies_postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: moviesdb
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: movie-api-pgadmin
    restart: unless-stopped
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@mail.com
      PGADMIN_DEFAULT_PASSWORD: dev
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
